//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace alps.net.api.src {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OWLTags {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OWLTags() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("alps.net.api.src.OWLTags", typeof(OWLTags).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abstract-pass-ont:.
        /// </summary>
        internal static string abstr {
            get {
                return ResourceManager.GetString("abstr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abstract-pass-ont:extends.
        /// </summary>
        internal static string abstrExtends {
            get {
                return ResourceManager.GetString("abstrExtends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abstract-pass-ont:implements.
        /// </summary>
        internal static string abstrImplements {
            get {
                return ResourceManager.GetString("abstrImplements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to belongsTo.
        /// </summary>
        internal static string belongsTo {
            get {
                return ResourceManager.GetString("belongsTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contains.
        /// </summary>
        internal static string contains {
            get {
                return ResourceManager.GetString("contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to containsBaseBehavior.
        /// </summary>
        internal static string containsBaseBehavior {
            get {
                return ResourceManager.GetString("containsBaseBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to containsBehavior.
        /// </summary>
        internal static string containsBehavior {
            get {
                return ResourceManager.GetString("containsBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to containsPayloadDescription.
        /// </summary>
        internal static string containsPayloadDescription {
            get {
                return ResourceManager.GetString("containsPayloadDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to extends.
        /// </summary>
        internal static string extends {
            get {
                return ResourceManager.GetString("extends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to guardedBy.
        /// </summary>
        internal static string guardedBy {
            get {
                return ResourceManager.GetString("guardedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to guards.
        /// </summary>
        internal static string guards {
            get {
                return ResourceManager.GetString("guards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to guardsBehavior.
        /// </summary>
        internal static string guardsBehavior {
            get {
                return ResourceManager.GetString("guardsBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to guardsState.
        /// </summary>
        internal static string guardsState {
            get {
                return ResourceManager.GetString("guardsState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hasDataDefintion.
        /// </summary>
        internal static string hasDataDefintion {
            get {
                return ResourceManager.GetString("hasDataDefintion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hasDataMappingFunction.
        /// </summary>
        internal static string hasDataMappingFunction {
            get {
                return ResourceManager.GetString("hasDataMappingFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hasDataMappingString.
        /// </summary>
        internal static string hasDataMappingString {
            get {
                return ResourceManager.GetString("hasDataMappingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hasDataType.
        /// </summary>
        internal static string hasDataType {
            get {
                return ResourceManager.GetString("hasDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hasEndState.
        /// </summary>
        internal static string hasEndState {
            get {
                return ResourceManager.GetString("hasEndState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hasExecutionMappingDefinition.
        /// </summary>
        internal static string hasExecutionMappingDefinition {
            get {
                return ResourceManager.GetString("hasExecutionMappingDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hasFeelExpressionAsDataMapping.
        /// </summary>
        internal static string hasFeelExpressionAsDataMapping {
            get {
                return ResourceManager.GetString("hasFeelExpressionAsDataMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hasFunctionSpecification.
        /// </summary>
        internal static string hasFunctionSpecification {
            get {
                return ResourceManager.GetString("hasFunctionSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hasHandlingStrategy.
        /// </summary>
        internal static string hasHandlingStrategy {
            get {
                return ResourceManager.GetString("hasHandlingStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hasIncomingMessageExchange.
        /// </summary>
        internal static string hasIncomingMessageExchange {
            get {
                return ResourceManager.GetString("hasIncomingMessageExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hasIncomingTransition.
        /// </summary>
        internal static string hasIncomingTransition {
            get {
                return ResourceManager.GetString("hasIncomingTransition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hasInitialState.
        /// </summary>
        internal static string hasInitialState {
            get {
                return ResourceManager.GetString("hasInitialState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hasInitialStateOfBehavior.
        /// </summary>
        internal static string hasInitialStateOfBehavior {
            get {
                return ResourceManager.GetString("hasInitialStateOfBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hasInputPoolConstraint.
        /// </summary>
        internal static string hasInputPoolConstraint {
            get {
                return ResourceManager.GetString("hasInputPoolConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hasMaximumSubjectInstanceRestriction.
        /// </summary>
        internal static string hasInstanceRestriction {
            get {
                return ResourceManager.GetString("hasInstanceRestriction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hasLimit.
        /// </summary>
        internal static string hasLimit {
            get {
                return ResourceManager.GetString("hasLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hasMessageType.
        /// </summary>
        internal static string hasMessageType {
            get {
                return ResourceManager.GetString("hasMessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hasModelComponentID.
        /// </summary>
        internal static string hasModelComponentID {
            get {
                return ResourceManager.GetString("hasModelComponentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hasModelComponentLabel.
        /// </summary>
        internal static string hasModelComponentLabel {
            get {
                return ResourceManager.GetString("hasModelComponentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hasMultiReceiveLowerBound.
        /// </summary>
        internal static string hasMultiReceiveLowerBound {
            get {
                return ResourceManager.GetString("hasMultiReceiveLowerBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hasMultiReceiveUpperBound.
        /// </summary>
        internal static string hasMultiReceiveUpperBound {
            get {
                return ResourceManager.GetString("hasMultiReceiveUpperBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hasMultiSendLowerBound.
        /// </summary>
        internal static string hasMultiSendLowerBound {
            get {
                return ResourceManager.GetString("hasMultiSendLowerBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hasMultiSendUpperBound.
        /// </summary>
        internal static string hasMultiSendUpperBound {
            get {
                return ResourceManager.GetString("hasMultiSendUpperBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hasOutgoingMessageExchange.
        /// </summary>
        internal static string hasOutgoingMessageExchange {
            get {
                return ResourceManager.GetString("hasOutgoingMessageExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hasOutgoingTransition.
        /// </summary>
        internal static string hasOutgoingTransition {
            get {
                return ResourceManager.GetString("hasOutgoingTransition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hasPriorityNumber.
        /// </summary>
        internal static string hasPriorityNumber {
            get {
                return ResourceManager.GetString("hasPriorityNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hasReceiver.
        /// </summary>
        internal static string hasReceiver {
            get {
                return ResourceManager.GetString("hasReceiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hasReceiveType.
        /// </summary>
        internal static string hasReceiveType {
            get {
                return ResourceManager.GetString("hasReceiveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hasSender.
        /// </summary>
        internal static string hasSender {
            get {
                return ResourceManager.GetString("hasSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hasSendType.
        /// </summary>
        internal static string hasSendType {
            get {
                return ResourceManager.GetString("hasSendType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hasSourceState.
        /// </summary>
        internal static string hasSourceState {
            get {
                return ResourceManager.GetString("hasSourceState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hasStartSubject.
        /// </summary>
        internal static string hasStartSubject {
            get {
                return ResourceManager.GetString("hasStartSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hasTargetState.
        /// </summary>
        internal static string hasTargetState {
            get {
                return ResourceManager.GetString("hasTargetState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hasTimeValue.
        /// </summary>
        internal static string hasTimeValue {
            get {
                return ResourceManager.GetString("hasTimeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hasToolSpecificDefinition.
        /// </summary>
        internal static string hasToolSpecificDefinition {
            get {
                return ResourceManager.GetString("hasToolSpecificDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hasTransitionCondition.
        /// </summary>
        internal static string hasTransitionCondition {
            get {
                return ResourceManager.GetString("hasTransitionCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to implements.
        /// </summary>
        internal static string implements {
            get {
                return ResourceManager.GetString("implements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to isOptionalToEndChoiceSegmentPath.
        /// </summary>
        internal static string isOptionalToEndChoiceSegmentPath {
            get {
                return ResourceManager.GetString("isOptionalToEndChoiceSegmentPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to isOptionalToStartChoiceSegmentPath.
        /// </summary>
        internal static string isOptionalToStartChoiceSegmentPath {
            get {
                return ResourceManager.GetString("isOptionalToStartChoiceSegmentPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NamedIndividual.
        /// </summary>
        internal static string NamedIndividual {
            get {
                return ResourceManager.GetString("NamedIndividual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rdfs:comment.
        /// </summary>
        internal static string rdfsComment {
            get {
                return ResourceManager.GetString("rdfsComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rdf:type.
        /// </summary>
        internal static string rdfType {
            get {
                return ResourceManager.GetString("rdfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to references.
        /// </summary>
        internal static string references {
            get {
                return ResourceManager.GetString("references", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to referencesMacroBehavior.
        /// </summary>
        internal static string referencesMacroBehavior {
            get {
                return ResourceManager.GetString("referencesMacroBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to requiresMessageSentFrom.
        /// </summary>
        internal static string requiresMessageSentFrom {
            get {
                return ResourceManager.GetString("requiresMessageSentFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to requiresMessageSentTo.
        /// </summary>
        internal static string requiresMessageSentTo {
            get {
                return ResourceManager.GetString("requiresMessageSentTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to requiresPerformedMessageExchange.
        /// </summary>
        internal static string requiresPerformedMessageExchange {
            get {
                return ResourceManager.GetString("requiresPerformedMessageExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to requiresReceptionOfMessage.
        /// </summary>
        internal static string requiresReceptionOfMessage {
            get {
                return ResourceManager.GetString("requiresReceptionOfMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to requiresSendingOfMessage.
        /// </summary>
        internal static string requiresSendingOfMessage {
            get {
                return ResourceManager.GetString("requiresSendingOfMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:.
        /// </summary>
        internal static string std {
            get {
                return ResourceManager.GetString("std", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:belongsTo.
        /// </summary>
        internal static string stdBelongsTo {
            get {
                return ResourceManager.GetString("stdBelongsTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:contains.
        /// </summary>
        internal static string stdContains {
            get {
                return ResourceManager.GetString("stdContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:containsBaseBehavior.
        /// </summary>
        internal static string stdContainsBaseBehavior {
            get {
                return ResourceManager.GetString("stdContainsBaseBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:containsBehavior.
        /// </summary>
        internal static string stdContainsBehavior {
            get {
                return ResourceManager.GetString("stdContainsBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:containsPayloadDescription.
        /// </summary>
        internal static string stdContainsPayloadDescription {
            get {
                return ResourceManager.GetString("stdContainsPayloadDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:guardedBy.
        /// </summary>
        internal static string stdGuardedBy {
            get {
                return ResourceManager.GetString("stdGuardedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:guards.
        /// </summary>
        internal static string stdGuards {
            get {
                return ResourceManager.GetString("stdGuards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:guardsBehavior.
        /// </summary>
        internal static string stdGuardsBehavior {
            get {
                return ResourceManager.GetString("stdGuardsBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:guardsState.
        /// </summary>
        internal static string stdGuardsState {
            get {
                return ResourceManager.GetString("stdGuardsState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:hasDataDefintion.
        /// </summary>
        internal static string stdHasDataDefintion {
            get {
                return ResourceManager.GetString("stdHasDataDefintion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:hasDataMappingFunction.
        /// </summary>
        internal static string stdHasDataMappingFunction {
            get {
                return ResourceManager.GetString("stdHasDataMappingFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:hasDataMappingString.
        /// </summary>
        internal static string stdHasDataMappingString {
            get {
                return ResourceManager.GetString("stdHasDataMappingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:hasDataType.
        /// </summary>
        internal static string stdHasDataType {
            get {
                return ResourceManager.GetString("stdHasDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:hasEndState.
        /// </summary>
        internal static string stdHasEndState {
            get {
                return ResourceManager.GetString("stdHasEndState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:hasExecutionMappingDefinition.
        /// </summary>
        internal static string stdHasExecutionMappingDefinition {
            get {
                return ResourceManager.GetString("stdHasExecutionMappingDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:hasFeelExpressionAsDataMapping.
        /// </summary>
        internal static string stdHasFeelExpressionAsDataMapping {
            get {
                return ResourceManager.GetString("stdHasFeelExpressionAsDataMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:hasFunctionSpecification.
        /// </summary>
        internal static string stdHasFunctionSpecification {
            get {
                return ResourceManager.GetString("stdHasFunctionSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:hasHandlingStrategy.
        /// </summary>
        internal static string stdHasHandlingStrategy {
            get {
                return ResourceManager.GetString("stdHasHandlingStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:hasIncomingMessageExchange.
        /// </summary>
        internal static string stdHasIncomingMessageExchange {
            get {
                return ResourceManager.GetString("stdHasIncomingMessageExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:hasIncomingTransition.
        /// </summary>
        internal static string stdHasIncomingTransition {
            get {
                return ResourceManager.GetString("stdHasIncomingTransition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:hasInitialState.
        /// </summary>
        internal static string stdHasInitialState {
            get {
                return ResourceManager.GetString("stdHasInitialState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:hasInitialStateOfBehavior.
        /// </summary>
        internal static string stdHasInitialStateOfBehavior {
            get {
                return ResourceManager.GetString("stdHasInitialStateOfBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:hasInputPoolConstraint.
        /// </summary>
        internal static string stdHasInputPoolConstraint {
            get {
                return ResourceManager.GetString("stdHasInputPoolConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:hasMaximumSubjectInstanceRestriction.
        /// </summary>
        internal static string stdhasInstanceRestriction {
            get {
                return ResourceManager.GetString("stdhasInstanceRestriction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:hasLimit.
        /// </summary>
        internal static string stdHasLimit {
            get {
                return ResourceManager.GetString("stdHasLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:hasMessageType.
        /// </summary>
        internal static string stdHasMessageType {
            get {
                return ResourceManager.GetString("stdHasMessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:hasModelComponentID.
        /// </summary>
        internal static string stdHasModelComponentID {
            get {
                return ResourceManager.GetString("stdHasModelComponentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:hasModelComponentLabel.
        /// </summary>
        internal static string stdHasModelComponentLabel {
            get {
                return ResourceManager.GetString("stdHasModelComponentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:hasMultiReceiveLowerBound.
        /// </summary>
        internal static string stdHasMultiReceiveLowerBound {
            get {
                return ResourceManager.GetString("stdHasMultiReceiveLowerBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:hasMultiReceiveUpperBound.
        /// </summary>
        internal static string stdHasMultiReceiveUpperBound {
            get {
                return ResourceManager.GetString("stdHasMultiReceiveUpperBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:hasMultiSendLowerBound.
        /// </summary>
        internal static string stdHasMultiSendLowerBound {
            get {
                return ResourceManager.GetString("stdHasMultiSendLowerBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:hasMultiSendUpperBound.
        /// </summary>
        internal static string stdHasMultiSendUpperBound {
            get {
                return ResourceManager.GetString("stdHasMultiSendUpperBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:hasOutgoingMessageExchange.
        /// </summary>
        internal static string stdHasOutgoingMessageExchange {
            get {
                return ResourceManager.GetString("stdHasOutgoingMessageExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:hasOutgoingTransition.
        /// </summary>
        internal static string stdHasOutgoingTransition {
            get {
                return ResourceManager.GetString("stdHasOutgoingTransition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:hasPriorityNumber.
        /// </summary>
        internal static string stdHasPriorityNumber {
            get {
                return ResourceManager.GetString("stdHasPriorityNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:hasReceiver.
        /// </summary>
        internal static string stdHasReceiver {
            get {
                return ResourceManager.GetString("stdHasReceiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:hasReceiveType.
        /// </summary>
        internal static string stdHasReceiveType {
            get {
                return ResourceManager.GetString("stdHasReceiveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:hasSender.
        /// </summary>
        internal static string stdHasSender {
            get {
                return ResourceManager.GetString("stdHasSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:hasSendType.
        /// </summary>
        internal static string stdHasSendType {
            get {
                return ResourceManager.GetString("stdHasSendType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:hasSourceState.
        /// </summary>
        internal static string stdHasSourceState {
            get {
                return ResourceManager.GetString("stdHasSourceState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:hasStartSubject.
        /// </summary>
        internal static string stdHasStartSubject {
            get {
                return ResourceManager.GetString("stdHasStartSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:hasTargetState.
        /// </summary>
        internal static string stdHasTargetState {
            get {
                return ResourceManager.GetString("stdHasTargetState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:hasTimeValue.
        /// </summary>
        internal static string stdHasTimeValue {
            get {
                return ResourceManager.GetString("stdHasTimeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:hasToolSpecificDefinition.
        /// </summary>
        internal static string stdHasToolSpecificDefinition {
            get {
                return ResourceManager.GetString("stdHasToolSpecificDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:hasTransitionCondition.
        /// </summary>
        internal static string stdHasTransitionCondition {
            get {
                return ResourceManager.GetString("stdHasTransitionCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:isOptionalToEndChoiceSegmentPath.
        /// </summary>
        internal static string stdIsOptionalToEndChoiceSegmentPath {
            get {
                return ResourceManager.GetString("stdIsOptionalToEndChoiceSegmentPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:isOptionalToStartChoiceSegmentPath.
        /// </summary>
        internal static string stdIsOptionalToStartChoiceSegmentPath {
            get {
                return ResourceManager.GetString("stdIsOptionalToStartChoiceSegmentPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to owl:NamedIndividual.
        /// </summary>
        internal static string stdNamedIndividual {
            get {
                return ResourceManager.GetString("stdNamedIndividual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:references.
        /// </summary>
        internal static string stdReferences {
            get {
                return ResourceManager.GetString("stdReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:referencesMacroBehavior.
        /// </summary>
        internal static string stdReferencesMacroBehavior {
            get {
                return ResourceManager.GetString("stdReferencesMacroBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:requiresMessageSentFrom.
        /// </summary>
        internal static string stdRequiresMessageSentFrom {
            get {
                return ResourceManager.GetString("stdRequiresMessageSentFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:requiresMessageSentTo.
        /// </summary>
        internal static string stdRequiresMessageSentTo {
            get {
                return ResourceManager.GetString("stdRequiresMessageSentTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:requiresPerformedMessageExchange.
        /// </summary>
        internal static string stdRequiresPerformedMessageExchange {
            get {
                return ResourceManager.GetString("stdRequiresPerformedMessageExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:requiresReceptionOfMessage.
        /// </summary>
        internal static string stdRequiresReceptionOfMessage {
            get {
                return ResourceManager.GetString("stdRequiresReceptionOfMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:requiresSendingOfMessage.
        /// </summary>
        internal static string stdRequiresSendingOfMessage {
            get {
                return ResourceManager.GetString("stdRequiresSendingOfMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to type.
        /// </summary>
        internal static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xsd:nonNegativeInteger.
        /// </summary>
        internal static string xsdDataTypeNonNegativeInt {
            get {
                return ResourceManager.GetString("xsdDataTypeNonNegativeInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xsd:positiveInteger.
        /// </summary>
        internal static string xsdDataTypePositiveInteger {
            get {
                return ResourceManager.GetString("xsdDataTypePositiveInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xsd:string.
        /// </summary>
        internal static string xsdDataTypeString {
            get {
                return ResourceManager.GetString("xsdDataTypeString", resourceCulture);
            }
        }
    }
}
