//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace alps.net.api.src {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OWLTags {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OWLTags() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("alps.net.api.src.OWLTags", typeof(OWLTags).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die abstract-pass-ont: ähnelt.
        /// </summary>
        internal static string abstr {
            get {
                return ResourceManager.GetString("abstr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die extends ähnelt.
        /// </summary>
        internal static string abstrExtends {
            get {
                return ResourceManager.GetString("abstrExtends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die has2DPageRatio ähnelt.
        /// </summary>
        internal static string abstrHas2DPageRatio {
            get {
                return ResourceManager.GetString("abstrHas2DPageRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hasRelative2D_BeginX ähnelt.
        /// </summary>
        internal static string abstrHasRelative2D_BeginX {
            get {
                return ResourceManager.GetString("abstrHasRelative2D_BeginX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die abtsrHasRelative2D_BeginY ähnelt.
        /// </summary>
        internal static string abstrHasRelative2D_BeginY {
            get {
                return ResourceManager.GetString("abstrHasRelative2D_BeginY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hasRelative2D_EndX ähnelt.
        /// </summary>
        internal static string abstrHasRelative2D_EndX {
            get {
                return ResourceManager.GetString("abstrHasRelative2D_EndX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hasRelative2D_EndY ähnelt.
        /// </summary>
        internal static string abstrHasRelative2D_EndY {
            get {
                return ResourceManager.GetString("abstrHasRelative2D_EndY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hasRelative2D_Height ähnelt.
        /// </summary>
        internal static string abstrHasRelative2D_Height {
            get {
                return ResourceManager.GetString("abstrHasRelative2D_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hasRelative2D_PosX ähnelt.
        /// </summary>
        internal static string abstrHasRelative2D_PosX {
            get {
                return ResourceManager.GetString("abstrHasRelative2D_PosX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hasRelative2D_PosY ähnelt.
        /// </summary>
        internal static string abstrHasRelative2D_PosY {
            get {
                return ResourceManager.GetString("abstrHasRelative2D_PosY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hasRelative2D_Width ähnelt.
        /// </summary>
        internal static string abstrHasRelative2D_Width {
            get {
                return ResourceManager.GetString("abstrHasRelative2D_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hasSimpleSimBilledWaitingTime ähnelt.
        /// </summary>
        internal static string abstrHasSimpleSimBilledWaitingTime {
            get {
                return ResourceManager.GetString("abstrHasSimpleSimBilledWaitingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hasSimpleSimCostPerExecution ähnelt.
        /// </summary>
        internal static string abstrHasSimpleSimCostPerExecution {
            get {
                return ResourceManager.GetString("abstrHasSimpleSimCostPerExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hasSimpleSimDurationDeviation ähnelt.
        /// </summary>
        internal static string abstrHasSimpleSimDurationDeviation {
            get {
                return ResourceManager.GetString("abstrHasSimpleSimDurationDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hasSimpleSimDurationMaxValue ähnelt.
        /// </summary>
        internal static string abstrHasSimpleSimDurationMaxValue {
            get {
                return ResourceManager.GetString("abstrHasSimpleSimDurationMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hasSimpleSimDurationMeanValue ähnelt.
        /// </summary>
        internal static string abstrHasSimpleSimDurationMeanValue {
            get {
                return ResourceManager.GetString("abstrHasSimpleSimDurationMeanValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hasSimpleSimDurationMinValue ähnelt.
        /// </summary>
        internal static string abstrHasSimpleSimDurationMinValue {
            get {
                return ResourceManager.GetString("abstrHasSimpleSimDurationMinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hasSimpleSimEndStayChance ähnelt.
        /// </summary>
        internal static string abstrHasSimpleSimEndStayChance {
            get {
                return ResourceManager.GetString("abstrHasSimpleSimEndStayChance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hasExecutionCostPerHour ähnelt.
        /// </summary>
        internal static string abstrHasSimpleSimExecutionCostPerHour {
            get {
                return ResourceManager.GetString("abstrHasSimpleSimExecutionCostPerHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hasSimpleSimInterfaceSubjectResponseDefinition ähnelt.
        /// </summary>
        internal static string abstrHasSimpleSimInterfaceSubjectResponseDefinition {
            get {
                return ResourceManager.GetString("abstrHasSimpleSimInterfaceSubjectResponseDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hasSimpleSimiVSMProcessQuantity ähnelt.
        /// </summary>
        internal static string abstrHasSimpleSimiVSMProcessQuantity {
            get {
                return ResourceManager.GetString("abstrHasSimpleSimiVSMProcessQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hasSimpleSimiVSMQualityRate ähnelt.
        /// </summary>
        internal static string abstrHasSimpleSimiVSMQualityRate {
            get {
                return ResourceManager.GetString("abstrHasSimpleSimiVSMQualityRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hasSimpleSimChoiceChance ähnelt.
        /// </summary>
        internal static string abstrHasSimpleSimTransitionChoiceChance {
            get {
                return ResourceManager.GetString("abstrHasSimpleSimTransitionChoiceChance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hasSimpleSimVSMAvailability ähnelt.
        /// </summary>
        internal static string abstrHasSimpleSimVSMAvailability {
            get {
                return ResourceManager.GetString("abstrHasSimpleSimVSMAvailability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hasSimpleSimVSMMessageType ähnelt.
        /// </summary>
        internal static string abstrHasSimpleSimVSMMessageType {
            get {
                return ResourceManager.GetString("abstrHasSimpleSimVSMMessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hasSimpleSimVSMSubjectType ähnelt.
        /// </summary>
        internal static string abstrHasSimpleSimVSMSubjectType {
            get {
                return ResourceManager.GetString("abstrHasSimpleSimVSMSubjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hasSimpleSimVSMTimeCategory ähnelt.
        /// </summary>
        internal static string abstrHasSimpleSimVSMTimeCategory {
            get {
                return ResourceManager.GetString("abstrHasSimpleSimVSMTimeCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die abstract-pass-ont:implements ähnelt.
        /// </summary>
        internal static string abstrImplements {
            get {
                return ResourceManager.GetString("abstrImplements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die belongsTo ähnelt.
        /// </summary>
        internal static string belongsTo {
            get {
                return ResourceManager.GetString("belongsTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die BusinessDayTimerTransition ähnelt.
        /// </summary>
        internal static string BusinessDayTimerTransitionClassName {
            get {
                return ResourceManager.GetString("BusinessDayTimerTransitionClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die BusinessDayTimerTransitionCondition ähnelt.
        /// </summary>
        internal static string BusinessDayTimerTransitionConditionClassName {
            get {
                return ResourceManager.GetString("BusinessDayTimerTransitionConditionClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CalendarBasedReminderTransition ähnelt.
        /// </summary>
        internal static string CalendarBasedReminderTransitionClassName {
            get {
                return ResourceManager.GetString("CalendarBasedReminderTransitionClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CalendarBasedReminderTransitionCondition ähnelt.
        /// </summary>
        internal static string CalendarBasedReminderTransitionConditionClassName {
            get {
                return ResourceManager.GetString("CalendarBasedReminderTransitionConditionClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die contains ähnelt.
        /// </summary>
        internal static string contains {
            get {
                return ResourceManager.GetString("contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die containsBaseBehavior ähnelt.
        /// </summary>
        internal static string containsBaseBehavior {
            get {
                return ResourceManager.GetString("containsBaseBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die containsBehavior ähnelt.
        /// </summary>
        internal static string containsBehavior {
            get {
                return ResourceManager.GetString("containsBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die containsPayloadDescription ähnelt.
        /// </summary>
        internal static string containsPayloadDescription {
            get {
                return ResourceManager.GetString("containsPayloadDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DayTimeTimerTransition ähnelt.
        /// </summary>
        internal static string DayTimeTimerTransitionClassName {
            get {
                return ResourceManager.GetString("DayTimeTimerTransitionClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DayTimeTimerTransitionCondition ähnelt.
        /// </summary>
        internal static string DayTimeTimerTransitionConditionClassName {
            get {
                return ResourceManager.GetString("DayTimeTimerTransitionConditionClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die extends ähnelt.
        /// </summary>
        internal static string extends {
            get {
                return ResourceManager.GetString("extends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die guardedBy ähnelt.
        /// </summary>
        internal static string guardedBy {
            get {
                return ResourceManager.GetString("guardedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die guards ähnelt.
        /// </summary>
        internal static string guards {
            get {
                return ResourceManager.GetString("guards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die guardsBehavior ähnelt.
        /// </summary>
        internal static string guardsBehavior {
            get {
                return ResourceManager.GetString("guardsBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die guardsState ähnelt.
        /// </summary>
        internal static string guardsState {
            get {
                return ResourceManager.GetString("guardsState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hasBusinessDayDurationTimeOutTime ähnelt.
        /// </summary>
        internal static string hasBusinessDayDurationTimeOutTime {
            get {
                return ResourceManager.GetString("hasBusinessDayDurationTimeOutTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hasCalendarBasedFrequencyOrDate ähnelt.
        /// </summary>
        internal static string hasCalendarBasedFrequencyOrDate {
            get {
                return ResourceManager.GetString("hasCalendarBasedFrequencyOrDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hasCorrespondent ähnelt.
        /// </summary>
        internal static string hasCorrespondent {
            get {
                return ResourceManager.GetString("hasCorrespondent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hasDataDefintion ähnelt.
        /// </summary>
        internal static string hasDataDefintion {
            get {
                return ResourceManager.GetString("hasDataDefintion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hasDataMappingFunction ähnelt.
        /// </summary>
        internal static string hasDataMappingFunction {
            get {
                return ResourceManager.GetString("hasDataMappingFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hasDataMappingString ähnelt.
        /// </summary>
        internal static string hasDataMappingString {
            get {
                return ResourceManager.GetString("hasDataMappingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hasDataType ähnelt.
        /// </summary>
        internal static string hasDataType {
            get {
                return ResourceManager.GetString("hasDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hasDayTimeDurationTimeOutTime ähnelt.
        /// </summary>
        internal static string hasDayTimeDurationTimeOutTime {
            get {
                return ResourceManager.GetString("hasDayTimeDurationTimeOutTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hasDurationTimeOutTime ähnelt.
        /// </summary>
        internal static string hasDurationTimeOutTime {
            get {
                return ResourceManager.GetString("hasDurationTimeOutTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hasEndState ähnelt.
        /// </summary>
        internal static string hasEndState {
            get {
                return ResourceManager.GetString("hasEndState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hasExecutionMappingDefinition ähnelt.
        /// </summary>
        internal static string hasExecutionMappingDefinition {
            get {
                return ResourceManager.GetString("hasExecutionMappingDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hasFeelExpressionAsDataMapping ähnelt.
        /// </summary>
        internal static string hasFeelExpressionAsDataMapping {
            get {
                return ResourceManager.GetString("hasFeelExpressionAsDataMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hasFunctionSpecification ähnelt.
        /// </summary>
        internal static string hasFunctionSpecification {
            get {
                return ResourceManager.GetString("hasFunctionSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hasHandlingStrategy ähnelt.
        /// </summary>
        internal static string hasHandlingStrategy {
            get {
                return ResourceManager.GetString("hasHandlingStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hasIncomingMessageExchange ähnelt.
        /// </summary>
        internal static string hasIncomingMessageExchange {
            get {
                return ResourceManager.GetString("hasIncomingMessageExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hasIncomingTransition ähnelt.
        /// </summary>
        internal static string hasIncomingTransition {
            get {
                return ResourceManager.GetString("hasIncomingTransition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hasInitialState ähnelt.
        /// </summary>
        internal static string hasInitialState {
            get {
                return ResourceManager.GetString("hasInitialState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hasInitialStateOfBehavior ähnelt.
        /// </summary>
        internal static string hasInitialStateOfBehavior {
            get {
                return ResourceManager.GetString("hasInitialStateOfBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hasInputPoolConstraint ähnelt.
        /// </summary>
        internal static string hasInputPoolConstraint {
            get {
                return ResourceManager.GetString("hasInputPoolConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hasMaximumSubjectInstanceRestriction ähnelt.
        /// </summary>
        internal static string hasInstanceRestriction {
            get {
                return ResourceManager.GetString("hasInstanceRestriction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hasLimit ähnelt.
        /// </summary>
        internal static string hasLimit {
            get {
                return ResourceManager.GetString("hasLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hasMessageType ähnelt.
        /// </summary>
        internal static string hasMessageType {
            get {
                return ResourceManager.GetString("hasMessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hasModelComponentID ähnelt.
        /// </summary>
        internal static string hasModelComponentID {
            get {
                return ResourceManager.GetString("hasModelComponentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hasModelComponentLabel ähnelt.
        /// </summary>
        internal static string hasModelComponentLabel {
            get {
                return ResourceManager.GetString("hasModelComponentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hasMultiReceiveLowerBound ähnelt.
        /// </summary>
        internal static string hasMultiReceiveLowerBound {
            get {
                return ResourceManager.GetString("hasMultiReceiveLowerBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hasMultiReceiveUpperBound ähnelt.
        /// </summary>
        internal static string hasMultiReceiveUpperBound {
            get {
                return ResourceManager.GetString("hasMultiReceiveUpperBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hasMultiSendLowerBound ähnelt.
        /// </summary>
        internal static string hasMultiSendLowerBound {
            get {
                return ResourceManager.GetString("hasMultiSendLowerBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hasMultiSendUpperBound ähnelt.
        /// </summary>
        internal static string hasMultiSendUpperBound {
            get {
                return ResourceManager.GetString("hasMultiSendUpperBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hasOutgoingMessageExchange ähnelt.
        /// </summary>
        internal static string hasOutgoingMessageExchange {
            get {
                return ResourceManager.GetString("hasOutgoingMessageExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hasOutgoingTransition ähnelt.
        /// </summary>
        internal static string hasOutgoingTransition {
            get {
                return ResourceManager.GetString("hasOutgoingTransition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hasPriorityNumber ähnelt.
        /// </summary>
        internal static string hasPriorityNumber {
            get {
                return ResourceManager.GetString("hasPriorityNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hasReceiver ähnelt.
        /// </summary>
        internal static string hasReceiver {
            get {
                return ResourceManager.GetString("hasReceiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hasReceiveType ähnelt.
        /// </summary>
        internal static string hasReceiveType {
            get {
                return ResourceManager.GetString("hasReceiveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hasReoccuranceFrequenyOrDate ähnelt.
        /// </summary>
        internal static string hasReoccuranceFrequenyOrDate {
            get {
                return ResourceManager.GetString("hasReoccuranceFrequenyOrDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hasSender ähnelt.
        /// </summary>
        internal static string hasSender {
            get {
                return ResourceManager.GetString("hasSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hasSendType ähnelt.
        /// </summary>
        internal static string hasSendType {
            get {
                return ResourceManager.GetString("hasSendType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hasSourceState ähnelt.
        /// </summary>
        internal static string hasSourceState {
            get {
                return ResourceManager.GetString("hasSourceState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hasStartSubject ähnelt.
        /// </summary>
        internal static string hasStartSubject {
            get {
                return ResourceManager.GetString("hasStartSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hasSubjectExecutionMapping ähnelt.
        /// </summary>
        internal static string hasSubjectExecutionMapping {
            get {
                return ResourceManager.GetString("hasSubjectExecutionMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hasTargetState ähnelt.
        /// </summary>
        internal static string hasTargetState {
            get {
                return ResourceManager.GetString("hasTargetState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hasTimeBasedReoccuranceFrequencyOrDate ähnelt.
        /// </summary>
        internal static string hasTimeBasedReoccuranceFrequencyOrDate {
            get {
                return ResourceManager.GetString("hasTimeBasedReoccuranceFrequencyOrDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hasTimeValue ähnelt.
        /// </summary>
        internal static string hasTimeValue {
            get {
                return ResourceManager.GetString("hasTimeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hasToolSpecificDefinition ähnelt.
        /// </summary>
        internal static string hasToolSpecificDefinition {
            get {
                return ResourceManager.GetString("hasToolSpecificDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hasTransitionCondition ähnelt.
        /// </summary>
        internal static string hasTransitionCondition {
            get {
                return ResourceManager.GetString("hasTransitionCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hasYearMonthDurationTimeOutTime ähnelt.
        /// </summary>
        internal static string hasYearMonthDurationTimeOutTime {
            get {
                return ResourceManager.GetString("hasYearMonthDurationTimeOutTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die implements ähnelt.
        /// </summary>
        internal static string implements {
            get {
                return ResourceManager.GetString("implements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die isOptionalToEndChoiceSegmentPath ähnelt.
        /// </summary>
        internal static string isOptionalToEndChoiceSegmentPath {
            get {
                return ResourceManager.GetString("isOptionalToEndChoiceSegmentPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die isOptionalToStartChoiceSegmentPath ähnelt.
        /// </summary>
        internal static string isOptionalToStartChoiceSegmentPath {
            get {
                return ResourceManager.GetString("isOptionalToStartChoiceSegmentPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die NamedIndividual ähnelt.
        /// </summary>
        internal static string NamedIndividual {
            get {
                return ResourceManager.GetString("NamedIndividual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die rdfs:comment ähnelt.
        /// </summary>
        internal static string rdfsComment {
            get {
                return ResourceManager.GetString("rdfsComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die rdf:type ähnelt.
        /// </summary>
        internal static string rdfType {
            get {
                return ResourceManager.GetString("rdfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die receiver ähnelt.
        /// </summary>
        internal static string receiver {
            get {
                return ResourceManager.GetString("receiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ReceiveTypeMultiReceiveFromAllKnown ähnelt.
        /// </summary>
        internal static string receiveTypeReceiveFromAll {
            get {
                return ResourceManager.GetString("receiveTypeReceiveFromAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ReceiveTypeMultiReceiveFromKnwon ähnelt.
        /// </summary>
        internal static string receiveTypeReceiveFromKnown {
            get {
                return ResourceManager.GetString("receiveTypeReceiveFromKnown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ReceiveTypeStandard ähnelt.
        /// </summary>
        internal static string receiveTypeStandard {
            get {
                return ResourceManager.GetString("receiveTypeStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die references ähnelt.
        /// </summary>
        internal static string references {
            get {
                return ResourceManager.GetString("references", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die referencesMacroBehavior ähnelt.
        /// </summary>
        internal static string referencesMacroBehavior {
            get {
                return ResourceManager.GetString("referencesMacroBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die requiresMessageSentFrom ähnelt.
        /// </summary>
        internal static string requiresMessageSentFrom {
            get {
                return ResourceManager.GetString("requiresMessageSentFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die requiresMessageSentTo ähnelt.
        /// </summary>
        internal static string requiresMessageSentTo {
            get {
                return ResourceManager.GetString("requiresMessageSentTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die requiresPerformedMessageExchange ähnelt.
        /// </summary>
        internal static string requiresPerformedMessageExchange {
            get {
                return ResourceManager.GetString("requiresPerformedMessageExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die requiresReceptionOfMessage ähnelt.
        /// </summary>
        internal static string requiresReceptionOfMessage {
            get {
                return ResourceManager.GetString("requiresReceptionOfMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die requiresSendingOfMessage ähnelt.
        /// </summary>
        internal static string requiresSendingOfMessage {
            get {
                return ResourceManager.GetString("requiresSendingOfMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die sender ähnelt.
        /// </summary>
        internal static string sender {
            get {
                return ResourceManager.GetString("sender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SendTypeMultiSendToAll ähnelt.
        /// </summary>
        internal static string sendTypeSendToAll {
            get {
                return ResourceManager.GetString("sendTypeSendToAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SendTypeMultiSendToKnown ähnelt.
        /// </summary>
        internal static string sendTypeSendToKnown {
            get {
                return ResourceManager.GetString("sendTypeSendToKnown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SendTypeMultiSendToNew ähnelt.
        /// </summary>
        internal static string sendTypeSendToNew {
            get {
                return ResourceManager.GetString("sendTypeSendToNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SendTypeStandard ähnelt.
        /// </summary>
        internal static string sendTypeStandard {
            get {
                return ResourceManager.GetString("sendTypeStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die standard-pass-ont: ähnelt.
        /// </summary>
        internal static string std {
            get {
                return ResourceManager.GetString("std", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die standard-pass-ont:belongsTo ähnelt.
        /// </summary>
        internal static string stdBelongsTo {
            get {
                return ResourceManager.GetString("stdBelongsTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die standard-pass-ont:contains ähnelt.
        /// </summary>
        internal static string stdContains {
            get {
                return ResourceManager.GetString("stdContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die standard-pass-ont:containsBaseBehavior ähnelt.
        /// </summary>
        internal static string stdContainsBaseBehavior {
            get {
                return ResourceManager.GetString("stdContainsBaseBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die standard-pass-ont:containsBehavior ähnelt.
        /// </summary>
        internal static string stdContainsBehavior {
            get {
                return ResourceManager.GetString("stdContainsBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die standard-pass-ont:containsPayloadDescription ähnelt.
        /// </summary>
        internal static string stdContainsPayloadDescription {
            get {
                return ResourceManager.GetString("stdContainsPayloadDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die standard-pass-ont:guardedBy ähnelt.
        /// </summary>
        internal static string stdGuardedBy {
            get {
                return ResourceManager.GetString("stdGuardedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die standard-pass-ont:guards ähnelt.
        /// </summary>
        internal static string stdGuards {
            get {
                return ResourceManager.GetString("stdGuards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die standard-pass-ont:guardsBehavior ähnelt.
        /// </summary>
        internal static string stdGuardsBehavior {
            get {
                return ResourceManager.GetString("stdGuardsBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die standard-pass-ont:guardsState ähnelt.
        /// </summary>
        internal static string stdGuardsState {
            get {
                return ResourceManager.GetString("stdGuardsState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die standard-pass-ont:hasBusinessDayDurationTimeOutTime ähnelt.
        /// </summary>
        internal static string stdHasBusinessDayDurationTimeOutTime {
            get {
                return ResourceManager.GetString("stdHasBusinessDayDurationTimeOutTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die standard-pass-ont:hasCalendarBasedFrequencyOrDate ähnelt.
        /// </summary>
        internal static string stdHasCalendarBasedFrequencyOrDate {
            get {
                return ResourceManager.GetString("stdHasCalendarBasedFrequencyOrDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die standard-pass-ont:hasCorrespondent ähnelt.
        /// </summary>
        internal static string stdHasCorrespondent {
            get {
                return ResourceManager.GetString("stdHasCorrespondent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die standard-pass-ont:hasDataDefintion ähnelt.
        /// </summary>
        internal static string stdHasDataDefintion {
            get {
                return ResourceManager.GetString("stdHasDataDefintion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die standard-pass-ont:hasDataMappingFunction ähnelt.
        /// </summary>
        internal static string stdHasDataMappingFunction {
            get {
                return ResourceManager.GetString("stdHasDataMappingFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die standard-pass-ont:hasDataMappingString ähnelt.
        /// </summary>
        internal static string stdHasDataMappingString {
            get {
                return ResourceManager.GetString("stdHasDataMappingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die standard-pass-ont:hasDataType ähnelt.
        /// </summary>
        internal static string stdHasDataType {
            get {
                return ResourceManager.GetString("stdHasDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die standard-pass-ont:hasDayTimeDurationTimeOutTime ähnelt.
        /// </summary>
        internal static string stdHasDayTimeDurationTimeOutTime {
            get {
                return ResourceManager.GetString("stdHasDayTimeDurationTimeOutTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die standard-pass-ont:hasDurationTimeOutTime ähnelt.
        /// </summary>
        internal static string stdHasDurationTimeOutTime {
            get {
                return ResourceManager.GetString("stdHasDurationTimeOutTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die standard-pass-ont:hasEndState ähnelt.
        /// </summary>
        internal static string stdHasEndState {
            get {
                return ResourceManager.GetString("stdHasEndState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die standard-pass-ont:hasExecutionMappingDefinition ähnelt.
        /// </summary>
        internal static string stdHasExecutionMappingDefinition {
            get {
                return ResourceManager.GetString("stdHasExecutionMappingDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die standard-pass-ont:hasFeelExpressionAsDataMapping ähnelt.
        /// </summary>
        internal static string stdHasFeelExpressionAsDataMapping {
            get {
                return ResourceManager.GetString("stdHasFeelExpressionAsDataMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die standard-pass-ont:hasFunctionSpecification ähnelt.
        /// </summary>
        internal static string stdHasFunctionSpecification {
            get {
                return ResourceManager.GetString("stdHasFunctionSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die standard-pass-ont:hasHandlingStrategy ähnelt.
        /// </summary>
        internal static string stdHasHandlingStrategy {
            get {
                return ResourceManager.GetString("stdHasHandlingStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die standard-pass-ont:hasIncomingMessageExchange ähnelt.
        /// </summary>
        internal static string stdHasIncomingMessageExchange {
            get {
                return ResourceManager.GetString("stdHasIncomingMessageExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die standard-pass-ont:hasIncomingTransition ähnelt.
        /// </summary>
        internal static string stdHasIncomingTransition {
            get {
                return ResourceManager.GetString("stdHasIncomingTransition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die standard-pass-ont:hasInitialState ähnelt.
        /// </summary>
        internal static string stdHasInitialState {
            get {
                return ResourceManager.GetString("stdHasInitialState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die standard-pass-ont:hasInputPoolConstraint ähnelt.
        /// </summary>
        internal static string stdHasInputPoolConstraint {
            get {
                return ResourceManager.GetString("stdHasInputPoolConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die standard-pass-ont:hasMaximumSubjectInstanceRestriction ähnelt.
        /// </summary>
        internal static string stdhasInstanceRestriction {
            get {
                return ResourceManager.GetString("stdhasInstanceRestriction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die standard-pass-ont:hasLimit ähnelt.
        /// </summary>
        internal static string stdHasLimit {
            get {
                return ResourceManager.GetString("stdHasLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die standard-pass-ont:hasMessageType ähnelt.
        /// </summary>
        internal static string stdHasMessageType {
            get {
                return ResourceManager.GetString("stdHasMessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die standard-pass-ont:hasModelComponentID ähnelt.
        /// </summary>
        internal static string stdHasModelComponentID {
            get {
                return ResourceManager.GetString("stdHasModelComponentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die standard-pass-ont:hasModelComponentLabel ähnelt.
        /// </summary>
        internal static string stdHasModelComponentLabel {
            get {
                return ResourceManager.GetString("stdHasModelComponentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die standard-pass-ont:hasMultiReceiveLowerBound ähnelt.
        /// </summary>
        internal static string stdHasMultiReceiveLowerBound {
            get {
                return ResourceManager.GetString("stdHasMultiReceiveLowerBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die standard-pass-ont:hasMultiReceiveUpperBound ähnelt.
        /// </summary>
        internal static string stdHasMultiReceiveUpperBound {
            get {
                return ResourceManager.GetString("stdHasMultiReceiveUpperBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die standard-pass-ont:hasMultiSendLowerBound ähnelt.
        /// </summary>
        internal static string stdHasMultiSendLowerBound {
            get {
                return ResourceManager.GetString("stdHasMultiSendLowerBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die standard-pass-ont:hasMultiSendUpperBound ähnelt.
        /// </summary>
        internal static string stdHasMultiSendUpperBound {
            get {
                return ResourceManager.GetString("stdHasMultiSendUpperBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die standard-pass-ont:hasOutgoingMessageExchange ähnelt.
        /// </summary>
        internal static string stdHasOutgoingMessageExchange {
            get {
                return ResourceManager.GetString("stdHasOutgoingMessageExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die standard-pass-ont:hasOutgoingTransition ähnelt.
        /// </summary>
        internal static string stdHasOutgoingTransition {
            get {
                return ResourceManager.GetString("stdHasOutgoingTransition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die standard-pass-ont:hasPriorityNumber ähnelt.
        /// </summary>
        internal static string stdHasPriorityNumber {
            get {
                return ResourceManager.GetString("stdHasPriorityNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die standard-pass-ont:hasReceiver ähnelt.
        /// </summary>
        internal static string stdHasReceiver {
            get {
                return ResourceManager.GetString("stdHasReceiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die standard-pass-ont:hasReceiveType ähnelt.
        /// </summary>
        internal static string stdHasReceiveType {
            get {
                return ResourceManager.GetString("stdHasReceiveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die standard-pass-ont:hasReoccuranceFrequenyOrDate ähnelt.
        /// </summary>
        internal static string stdHasReoccuranceFrequenyOrDate {
            get {
                return ResourceManager.GetString("stdHasReoccuranceFrequenyOrDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die standard-pass-ont:hasSender ähnelt.
        /// </summary>
        internal static string stdHasSender {
            get {
                return ResourceManager.GetString("stdHasSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die standard-pass-ont:hasSendType ähnelt.
        /// </summary>
        internal static string stdHasSendType {
            get {
                return ResourceManager.GetString("stdHasSendType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die standard-pass-ont:hasSourceState ähnelt.
        /// </summary>
        internal static string stdHasSourceState {
            get {
                return ResourceManager.GetString("stdHasSourceState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die standard-pass-ont:hasStartSubject ähnelt.
        /// </summary>
        internal static string stdHasStartSubject {
            get {
                return ResourceManager.GetString("stdHasStartSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die standard-pass-ont:hasTargetState ähnelt.
        /// </summary>
        internal static string stdHasTargetState {
            get {
                return ResourceManager.GetString("stdHasTargetState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die standard-pass-ont:hasTimeBasedReoccuranceFrequencyOrDate ähnelt.
        /// </summary>
        internal static string stdHasTimeBasedReoccuranceFrequencyOrDate {
            get {
                return ResourceManager.GetString("stdHasTimeBasedReoccuranceFrequencyOrDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die standard-pass-ont:hasTimeValue ähnelt.
        /// </summary>
        internal static string stdHasTimeValue {
            get {
                return ResourceManager.GetString("stdHasTimeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die standard-pass-ont:hasToolSpecificDefinition ähnelt.
        /// </summary>
        internal static string stdHasToolSpecificDefinition {
            get {
                return ResourceManager.GetString("stdHasToolSpecificDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die standard-pass-ont:hasTransitionCondition ähnelt.
        /// </summary>
        internal static string stdHasTransitionCondition {
            get {
                return ResourceManager.GetString("stdHasTransitionCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die standard-pass-ont:hasYearMonthDurationTimeOutTime ähnelt.
        /// </summary>
        internal static string stdHasYearMonthDurationTimeOutTime {
            get {
                return ResourceManager.GetString("stdHasYearMonthDurationTimeOutTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die standard-pass-ont:isOptionalToEndChoiceSegmentPath ähnelt.
        /// </summary>
        internal static string stdIsOptionalToEndChoiceSegmentPath {
            get {
                return ResourceManager.GetString("stdIsOptionalToEndChoiceSegmentPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die standard-pass-ont:isOptionalToStartChoiceSegmentPath ähnelt.
        /// </summary>
        internal static string stdIsOptionalToStartChoiceSegmentPath {
            get {
                return ResourceManager.GetString("stdIsOptionalToStartChoiceSegmentPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die owl:NamedIndividual ähnelt.
        /// </summary>
        internal static string stdNamedIndividual {
            get {
                return ResourceManager.GetString("stdNamedIndividual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die standard-pass-ont:receiver ähnelt.
        /// </summary>
        internal static string stdReceiver {
            get {
                return ResourceManager.GetString("stdReceiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die standard-pass-ont:ReceiveTypeMultiReceiveFromAllKnown ähnelt.
        /// </summary>
        internal static string stdReceiveTypeReceiveFromAll {
            get {
                return ResourceManager.GetString("stdReceiveTypeReceiveFromAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die standard-pass-ont:ReceiveTypeMultiReceiveFromKnwon ähnelt.
        /// </summary>
        internal static string stdReceiveTypeReceiveFromKnown {
            get {
                return ResourceManager.GetString("stdReceiveTypeReceiveFromKnown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die standard-pass-ont:ReceiveTypeStandard ähnelt.
        /// </summary>
        internal static string stdReceiveTypeStandard {
            get {
                return ResourceManager.GetString("stdReceiveTypeStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die standard-pass-ont:references ähnelt.
        /// </summary>
        internal static string stdReferences {
            get {
                return ResourceManager.GetString("stdReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die standard-pass-ont:referencesMacroBehavior ähnelt.
        /// </summary>
        internal static string stdReferencesMacroBehavior {
            get {
                return ResourceManager.GetString("stdReferencesMacroBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die standard-pass-ont:requiresMessageSentFrom ähnelt.
        /// </summary>
        internal static string stdRequiresMessageSentFrom {
            get {
                return ResourceManager.GetString("stdRequiresMessageSentFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die standard-pass-ont:requiresMessageSentTo ähnelt.
        /// </summary>
        internal static string stdRequiresMessageSentTo {
            get {
                return ResourceManager.GetString("stdRequiresMessageSentTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die standard-pass-ont:requiresPerformedMessageExchange ähnelt.
        /// </summary>
        internal static string stdRequiresPerformedMessageExchange {
            get {
                return ResourceManager.GetString("stdRequiresPerformedMessageExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die standard-pass-ont:requiresReceptionOfMessage ähnelt.
        /// </summary>
        internal static string stdRequiresReceptionOfMessage {
            get {
                return ResourceManager.GetString("stdRequiresReceptionOfMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die standard-pass-ont:requiresSendingOfMessage ähnelt.
        /// </summary>
        internal static string stdRequiresSendingOfMessage {
            get {
                return ResourceManager.GetString("stdRequiresSendingOfMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die standard-pass-ont:sender ähnelt.
        /// </summary>
        internal static string stdSender {
            get {
                return ResourceManager.GetString("stdSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die standard-pass-ont:SendTypeMultiSendToAll ähnelt.
        /// </summary>
        internal static string stdSendTypeSendToAll {
            get {
                return ResourceManager.GetString("stdSendTypeSendToAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die standard-pass-ont:SendTypeMultiSendToKnown ähnelt.
        /// </summary>
        internal static string stdSendTypeSendToKnown {
            get {
                return ResourceManager.GetString("stdSendTypeSendToKnown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die standard-pass-ont:SendTypeMultiSendToNew ähnelt.
        /// </summary>
        internal static string stdSendTypeSendToNew {
            get {
                return ResourceManager.GetString("stdSendTypeSendToNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die standard-pass-ont:SendTypeStandard ähnelt.
        /// </summary>
        internal static string stdSendTypeStandard {
            get {
                return ResourceManager.GetString("stdSendTypeStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die standard-pass-ont:StartSubject ähnelt.
        /// </summary>
        internal static string stdStartSubject {
            get {
                return ResourceManager.GetString("stdStartSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TimeBasedReminderTransition ähnelt.
        /// </summary>
        internal static string TimeBasedReminderTransitionClassName {
            get {
                return ResourceManager.GetString("TimeBasedReminderTransitionClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TimeBasedReminderTransitionCondition ähnelt.
        /// </summary>
        internal static string TimeBasedReminderTransitionConditionClassName {
            get {
                return ResourceManager.GetString("TimeBasedReminderTransitionConditionClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die type ähnelt.
        /// </summary>
        internal static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die xsd:nonNegativeInteger ähnelt.
        /// </summary>
        internal static string xsdDataTypeNonNegativeInt {
            get {
                return ResourceManager.GetString("xsdDataTypeNonNegativeInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die xsd:positiveInteger ähnelt.
        /// </summary>
        internal static string xsdDataTypePositiveInteger {
            get {
                return ResourceManager.GetString("xsdDataTypePositiveInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die xsd:string ähnelt.
        /// </summary>
        internal static string xsdDataTypeString {
            get {
                return ResourceManager.GetString("xsdDataTypeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die xsd:dayTimeDuration ähnelt.
        /// </summary>
        internal static string xsdDayTimeDuration {
            get {
                return ResourceManager.GetString("xsdDayTimeDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die xsd:yearMonthDuration ähnelt.
        /// </summary>
        internal static string xsdYearMonthDuration {
            get {
                return ResourceManager.GetString("xsdYearMonthDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die YearMonthTimerTransition ähnelt.
        /// </summary>
        internal static string YearMonthTimerTransitionClassName {
            get {
                return ResourceManager.GetString("YearMonthTimerTransitionClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die YearMonthTimerTransitionCondition ähnelt.
        /// </summary>
        internal static string YearMonthTimerTransitionConditionClassName {
            get {
                return ResourceManager.GetString("YearMonthTimerTransitionConditionClassName", resourceCulture);
            }
        }
    }
}
