//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace alps.net.api.src
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OWLTags
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OWLTags()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("alps.net.api.src.OWLTags", typeof(OWLTags).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to abstract-pass-ont:.
        /// </summary>
        internal static string abstr
        {
            get
            {
                return ResourceManager.GetString("abstr", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to extends.
        /// </summary>
        internal static string abstrExtends
        {
            get
            {
                return ResourceManager.GetString("abstrExtends", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to has2DPageRatio.
        /// </summary>
        internal static string abstrHas2DPageRatio
        {
            get
            {
                return ResourceManager.GetString("abstrHas2DPageRatio", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to hasRelative2D_BeginX.
        /// </summary>
        internal static string abstrHasRelative2D_BeginX
        {
            get
            {
                return ResourceManager.GetString("abstrHasRelative2D_BeginX", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to abtsrHasRelative2D_BeginY.
        /// </summary>
        internal static string abstrHasRelative2D_BeginY
        {
            get
            {
                return ResourceManager.GetString("abstrHasRelative2D_BeginY", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to hasRelative2D_EndX.
        /// </summary>
        internal static string abstrHasRelative2D_EndX
        {
            get
            {
                return ResourceManager.GetString("abstrHasRelative2D_EndX", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to hasRelative2D_EndY.
        /// </summary>
        internal static string abstrHasRelative2D_EndY
        {
            get
            {
                return ResourceManager.GetString("abstrHasRelative2D_EndY", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to hasRelative2D_Height.
        /// </summary>
        internal static string abstrHasRelative2D_Height
        {
            get
            {
                return ResourceManager.GetString("abstrHasRelative2D_Height", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to hasRelative2D_PosX.
        /// </summary>
        internal static string abstrHasRelative2D_PosX
        {
            get
            {
                return ResourceManager.GetString("abstrHasRelative2D_PosX", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to hasRelative2D_PosY.
        /// </summary>
        internal static string abstrHasRelative2D_PosY
        {
            get
            {
                return ResourceManager.GetString("abstrHasRelative2D_PosY", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to hasRelative2D_Width.
        /// </summary>
        internal static string abstrHasRelative2D_Width
        {
            get
            {
                return ResourceManager.GetString("abstrHasRelative2D_Width", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to hasSimpleSimBilledWaitingTime.
        /// </summary>
        internal static string abstrHasSimpleSimBilledWaitingTime
        {
            get
            {
                return ResourceManager.GetString("abstrHasSimpleSimBilledWaitingTime", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to hasSimpleSimCostPerExecution.
        /// </summary>
        internal static string abstrHasSimpleSimCostPerExecution
        {
            get
            {
                return ResourceManager.GetString("abstrHasSimpleSimCostPerExecution", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to hasSimpleSimDurationDeviation.
        /// </summary>
        internal static string abstrHasSimpleSimDurationDeviation
        {
            get
            {
                return ResourceManager.GetString("abstrHasSimpleSimDurationDeviation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to hasSimpleSimDurationMaxValue.
        /// </summary>
        internal static string abstrHasSimpleSimDurationMaxValue
        {
            get
            {
                return ResourceManager.GetString("abstrHasSimpleSimDurationMaxValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to hasSimpleSimDurationMeanValue.
        /// </summary>
        internal static string abstrHasSimpleSimDurationMeanValue
        {
            get
            {
                return ResourceManager.GetString("abstrHasSimpleSimDurationMeanValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to hasSimpleSimDurationMinValue.
        /// </summary>
        internal static string abstrHasSimpleSimDurationMinValue
        {
            get
            {
                return ResourceManager.GetString("abstrHasSimpleSimDurationMinValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to hasSimpleSimEndStayChance.
        /// </summary>
        internal static string abstrHasSimpleSimEndStayChance
        {
            get
            {
                return ResourceManager.GetString("abstrHasSimpleSimEndStayChance", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to hasExecutionCostPerHour.
        /// </summary>
        internal static string abstrHasSimpleSimExecutionCostPerHour
        {
            get
            {
                return ResourceManager.GetString("abstrHasSimpleSimExecutionCostPerHour", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to hasSimpleSimInterfaceSubjectResponseDefinition.
        /// </summary>
        internal static string abstrHasSimpleSimInterfaceSubjectResponseDefinition
        {
            get
            {
                return ResourceManager.GetString("abstrHasSimpleSimInterfaceSubjectResponseDefinition", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to hasSimpleSimiVSMProcessQuantity.
        /// </summary>
        internal static string abstrHasSimpleSimiVSMProcessQuantity
        {
            get
            {
                return ResourceManager.GetString("abstrHasSimpleSimiVSMProcessQuantity", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to hasSimpleSimiVSMQualityRate.
        /// </summary>
        internal static string abstrHasSimpleSimiVSMQualityRate
        {
            get
            {
                return ResourceManager.GetString("abstrHasSimpleSimiVSMQualityRate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to hasSimpleSimChoiceChance.
        /// </summary>
        internal static string abstrHasSimpleSimTransitionChoiceChance
        {
            get
            {
                return ResourceManager.GetString("abstrHasSimpleSimTransitionChoiceChance", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to hasSimpleSimVSMAvailability.
        /// </summary>
        internal static string abstrHasSimpleSimVSMAvailability
        {
            get
            {
                return ResourceManager.GetString("abstrHasSimpleSimVSMAvailability", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to hasSimpleSimVSMMessageType.
        /// </summary>
        internal static string abstrHasSimpleSimVSMMessageType
        {
            get
            {
                return ResourceManager.GetString("abstrHasSimpleSimVSMMessageType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to hasSimpleSimVSMSubjectType.
        /// </summary>
        internal static string abstrHasSimpleSimVSMSubjectType
        {
            get
            {
                return ResourceManager.GetString("abstrHasSimpleSimVSMSubjectType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to hasSimpleSimVSMTimeCategory.
        /// </summary>
        internal static string abstrHasSimpleSimVSMTimeCategory
        {
            get
            {
                return ResourceManager.GetString("abstrHasSimpleSimVSMTimeCategory", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to abstract-pass-ont:implements.
        /// </summary>
        internal static string abstrImplements
        {
            get
            {
                return ResourceManager.GetString("abstrImplements", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to belongsTo.
        /// </summary>
        internal static string belongsTo
        {
            get
            {
                return ResourceManager.GetString("belongsTo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to BusinessDayTimerTransition.
        /// </summary>
        internal static string BusinessDayTimerTransitionClassName
        {
            get
            {
                return ResourceManager.GetString("BusinessDayTimerTransitionClassName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to BusinessDayTimerTransitionCondition.
        /// </summary>
        internal static string BusinessDayTimerTransitionConditionClassName
        {
            get
            {
                return ResourceManager.GetString("BusinessDayTimerTransitionConditionClassName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CalendarBasedReminderTransition.
        /// </summary>
        internal static string CalendarBasedReminderTransitionClassName
        {
            get
            {
                return ResourceManager.GetString("CalendarBasedReminderTransitionClassName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CalendarBasedReminderTransitionCondition.
        /// </summary>
        internal static string CalendarBasedReminderTransitionConditionClassName
        {
            get
            {
                return ResourceManager.GetString("CalendarBasedReminderTransitionConditionClassName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to contains.
        /// </summary>
        internal static string contains
        {
            get
            {
                return ResourceManager.GetString("contains", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to containsBaseBehavior.
        /// </summary>
        internal static string containsBaseBehavior
        {
            get
            {
                return ResourceManager.GetString("containsBaseBehavior", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to containsBehavior.
        /// </summary>
        internal static string containsBehavior
        {
            get
            {
                return ResourceManager.GetString("containsBehavior", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to containsPayloadDescription.
        /// </summary>
        internal static string containsPayloadDescription
        {
            get
            {
                return ResourceManager.GetString("containsPayloadDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DayTimeTimerTransition.
        /// </summary>
        internal static string DayTimeTimerTransitionClassName
        {
            get
            {
                return ResourceManager.GetString("DayTimeTimerTransitionClassName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DayTimeTimerTransitionCondition.
        /// </summary>
        internal static string DayTimeTimerTransitionConditionClassName
        {
            get
            {
                return ResourceManager.GetString("DayTimeTimerTransitionConditionClassName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to extends.
        /// </summary>
        internal static string extends
        {
            get
            {
                return ResourceManager.GetString("extends", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to guardedBy.
        /// </summary>
        internal static string guardedBy
        {
            get
            {
                return ResourceManager.GetString("guardedBy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to guards.
        /// </summary>
        internal static string guards
        {
            get
            {
                return ResourceManager.GetString("guards", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to guardsBehavior.
        /// </summary>
        internal static string guardsBehavior
        {
            get
            {
                return ResourceManager.GetString("guardsBehavior", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to guardsState.
        /// </summary>
        internal static string guardsState
        {
            get
            {
                return ResourceManager.GetString("guardsState", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to hasBusinessDayDurationTimeOutTime.
        /// </summary>
        internal static string hasBusinessDayDurationTimeOutTime
        {
            get
            {
                return ResourceManager.GetString("hasBusinessDayDurationTimeOutTime", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to hasCalendarBasedFrequencyOrDate.
        /// </summary>
        internal static string hasCalendarBasedFrequencyOrDate
        {
            get
            {
                return ResourceManager.GetString("hasCalendarBasedFrequencyOrDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to hasCorrespondent.
        /// </summary>
        internal static string hasCorrespondent
        {
            get
            {
                return ResourceManager.GetString("hasCorrespondent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to hasDataDefintion.
        /// </summary>
        internal static string hasDataDefintion
        {
            get
            {
                return ResourceManager.GetString("hasDataDefintion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to hasDataMappingFunction.
        /// </summary>
        internal static string hasDataMappingFunction
        {
            get
            {
                return ResourceManager.GetString("hasDataMappingFunction", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to hasDataMappingString.
        /// </summary>
        internal static string hasDataMappingString
        {
            get
            {
                return ResourceManager.GetString("hasDataMappingString", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to hasDataType.
        /// </summary>
        internal static string hasDataType
        {
            get
            {
                return ResourceManager.GetString("hasDataType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to hasDayTimeDurationTimeOutTime.
        /// </summary>
        internal static string hasDayTimeDurationTimeOutTime
        {
            get
            {
                return ResourceManager.GetString("hasDayTimeDurationTimeOutTime", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to hasDurationTimeOutTime.
        /// </summary>
        internal static string hasDurationTimeOutTime
        {
            get
            {
                return ResourceManager.GetString("hasDurationTimeOutTime", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to hasEndState.
        /// </summary>
        internal static string hasEndState
        {
            get
            {
                return ResourceManager.GetString("hasEndState", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to hasExecutionMappingDefinition.
        /// </summary>
        internal static string hasExecutionMappingDefinition
        {
            get
            {
                return ResourceManager.GetString("hasExecutionMappingDefinition", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to hasFeelExpressionAsDataMapping.
        /// </summary>
        internal static string hasFeelExpressionAsDataMapping
        {
            get
            {
                return ResourceManager.GetString("hasFeelExpressionAsDataMapping", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to hasFunctionSpecification.
        /// </summary>
        internal static string hasFunctionSpecification
        {
            get
            {
                return ResourceManager.GetString("hasFunctionSpecification", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to hasHandlingStrategy.
        /// </summary>
        internal static string hasHandlingStrategy
        {
            get
            {
                return ResourceManager.GetString("hasHandlingStrategy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to hasIncomingMessageExchange.
        /// </summary>
        internal static string hasIncomingMessageExchange
        {
            get
            {
                return ResourceManager.GetString("hasIncomingMessageExchange", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to hasIncomingTransition.
        /// </summary>
        internal static string hasIncomingTransition
        {
            get
            {
                return ResourceManager.GetString("hasIncomingTransition", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to hasInitialState.
        /// </summary>
        internal static string hasInitialState
        {
            get
            {
                return ResourceManager.GetString("hasInitialState", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to hasInitialStateOfBehavior.
        /// </summary>
        internal static string hasInitialStateOfBehavior
        {
            get
            {
                return ResourceManager.GetString("hasInitialStateOfBehavior", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to hasInputPoolConstraint.
        /// </summary>
        internal static string hasInputPoolConstraint
        {
            get
            {
                return ResourceManager.GetString("hasInputPoolConstraint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to hasMaximumSubjectInstanceRestriction.
        /// </summary>
        internal static string hasInstanceRestriction
        {
            get
            {
                return ResourceManager.GetString("hasInstanceRestriction", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to hasLimit.
        /// </summary>
        internal static string hasLimit
        {
            get
            {
                return ResourceManager.GetString("hasLimit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to hasMessageType.
        /// </summary>
        internal static string hasMessageType
        {
            get
            {
                return ResourceManager.GetString("hasMessageType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to hasModelComponentID.
        /// </summary>
        internal static string hasModelComponentID
        {
            get
            {
                return ResourceManager.GetString("hasModelComponentID", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to hasModelComponentLabel.
        /// </summary>
        internal static string hasModelComponentLabel
        {
            get
            {
                return ResourceManager.GetString("hasModelComponentLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to hasMultiReceiveLowerBound.
        /// </summary>
        internal static string hasMultiReceiveLowerBound
        {
            get
            {
                return ResourceManager.GetString("hasMultiReceiveLowerBound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to hasMultiReceiveUpperBound.
        /// </summary>
        internal static string hasMultiReceiveUpperBound
        {
            get
            {
                return ResourceManager.GetString("hasMultiReceiveUpperBound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to hasMultiSendLowerBound.
        /// </summary>
        internal static string hasMultiSendLowerBound
        {
            get
            {
                return ResourceManager.GetString("hasMultiSendLowerBound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to hasMultiSendUpperBound.
        /// </summary>
        internal static string hasMultiSendUpperBound
        {
            get
            {
                return ResourceManager.GetString("hasMultiSendUpperBound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to hasOutgoingMessageExchange.
        /// </summary>
        internal static string hasOutgoingMessageExchange
        {
            get
            {
                return ResourceManager.GetString("hasOutgoingMessageExchange", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to hasOutgoingTransition.
        /// </summary>
        internal static string hasOutgoingTransition
        {
            get
            {
                return ResourceManager.GetString("hasOutgoingTransition", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to hasPriorityNumber.
        /// </summary>
        internal static string hasPriorityNumber
        {
            get
            {
                return ResourceManager.GetString("hasPriorityNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to hasReceiver.
        /// </summary>
        internal static string hasReceiver
        {
            get
            {
                return ResourceManager.GetString("hasReceiver", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to hasReceiveType.
        /// </summary>
        internal static string hasReceiveType
        {
            get
            {
                return ResourceManager.GetString("hasReceiveType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to hasReoccuranceFrequenyOrDate.
        /// </summary>
        internal static string hasReoccuranceFrequenyOrDate
        {
            get
            {
                return ResourceManager.GetString("hasReoccuranceFrequenyOrDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to hasSender.
        /// </summary>
        internal static string hasSender
        {
            get
            {
                return ResourceManager.GetString("hasSender", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to hasSendType.
        /// </summary>
        internal static string hasSendType
        {
            get
            {
                return ResourceManager.GetString("hasSendType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to hasSourceState.
        /// </summary>
        internal static string hasSourceState
        {
            get
            {
                return ResourceManager.GetString("hasSourceState", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to hasStartSubject.
        /// </summary>
        internal static string hasStartSubject
        {
            get
            {
                return ResourceManager.GetString("hasStartSubject", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to hasSubjectExecutionMapping.
        /// </summary>
        internal static string hasSubjectExecutionMapping
        {
            get
            {
                return ResourceManager.GetString("hasSubjectExecutionMapping", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to hasTargetState.
        /// </summary>
        internal static string hasTargetState
        {
            get
            {
                return ResourceManager.GetString("hasTargetState", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to hasTimeBasedReoccuranceFrequencyOrDate.
        /// </summary>
        internal static string hasTimeBasedReoccuranceFrequencyOrDate
        {
            get
            {
                return ResourceManager.GetString("hasTimeBasedReoccuranceFrequencyOrDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to hasTimeValue.
        /// </summary>
        internal static string hasTimeValue
        {
            get
            {
                return ResourceManager.GetString("hasTimeValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to hasToolSpecificDefinition.
        /// </summary>
        internal static string hasToolSpecificDefinition
        {
            get
            {
                return ResourceManager.GetString("hasToolSpecificDefinition", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to hasTransitionCondition.
        /// </summary>
        internal static string hasTransitionCondition
        {
            get
            {
                return ResourceManager.GetString("hasTransitionCondition", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to hasYearMonthDurationTimeOutTime.
        /// </summary>
        internal static string hasYearMonthDurationTimeOutTime
        {
            get
            {
                return ResourceManager.GetString("hasYearMonthDurationTimeOutTime", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to implements.
        /// </summary>
        internal static string implements
        {
            get
            {
                return ResourceManager.GetString("implements", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to isOptionalToEndChoiceSegmentPath.
        /// </summary>
        internal static string isOptionalToEndChoiceSegmentPath
        {
            get
            {
                return ResourceManager.GetString("isOptionalToEndChoiceSegmentPath", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to isOptionalToStartChoiceSegmentPath.
        /// </summary>
        internal static string isOptionalToStartChoiceSegmentPath
        {
            get
            {
                return ResourceManager.GetString("isOptionalToStartChoiceSegmentPath", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to NamedIndividual.
        /// </summary>
        internal static string NamedIndividual
        {
            get
            {
                return ResourceManager.GetString("NamedIndividual", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to http://www.w3.org/2002/07/owl#NamedIndividual.
        /// </summary>
        internal static string owlNamedIndividualFull
        {
            get
            {
                return ResourceManager.GetString("owlNamedIndividualFull", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to rdfs:comment.
        /// </summary>
        internal static string rdfsComment
        {
            get
            {
                return ResourceManager.GetString("rdfsComment", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to rdf:type.
        /// </summary>
        internal static string rdfType
        {
            get
            {
                return ResourceManager.GetString("rdfType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to http://www.w3.org/1999/02/22-rdf-syntax-ns#type.
        /// </summary>
        internal static string rdfTypeFull
        {
            get
            {
                return ResourceManager.GetString("rdfTypeFull", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to receiver.
        /// </summary>
        internal static string receiver
        {
            get
            {
                return ResourceManager.GetString("receiver", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ReceiveTypeMultiReceiveFromAllKnown.
        /// </summary>
        internal static string receiveTypeReceiveFromAll
        {
            get
            {
                return ResourceManager.GetString("receiveTypeReceiveFromAll", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ReceiveTypeMultiReceiveFromKnwon.
        /// </summary>
        internal static string receiveTypeReceiveFromKnown
        {
            get
            {
                return ResourceManager.GetString("receiveTypeReceiveFromKnown", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ReceiveTypeStandard.
        /// </summary>
        internal static string receiveTypeStandard
        {
            get
            {
                return ResourceManager.GetString("receiveTypeStandard", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to references.
        /// </summary>
        internal static string references
        {
            get
            {
                return ResourceManager.GetString("references", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to referencesMacroBehavior.
        /// </summary>
        internal static string referencesMacroBehavior
        {
            get
            {
                return ResourceManager.GetString("referencesMacroBehavior", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to requiresMessageSentFrom.
        /// </summary>
        internal static string requiresMessageSentFrom
        {
            get
            {
                return ResourceManager.GetString("requiresMessageSentFrom", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to requiresMessageSentTo.
        /// </summary>
        internal static string requiresMessageSentTo
        {
            get
            {
                return ResourceManager.GetString("requiresMessageSentTo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to requiresPerformedMessageExchange.
        /// </summary>
        internal static string requiresPerformedMessageExchange
        {
            get
            {
                return ResourceManager.GetString("requiresPerformedMessageExchange", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to requiresReceptionOfMessage.
        /// </summary>
        internal static string requiresReceptionOfMessage
        {
            get
            {
                return ResourceManager.GetString("requiresReceptionOfMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to requiresSendingOfMessage.
        /// </summary>
        internal static string requiresSendingOfMessage
        {
            get
            {
                return ResourceManager.GetString("requiresSendingOfMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to sender.
        /// </summary>
        internal static string sender
        {
            get
            {
                return ResourceManager.GetString("sender", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SendTypeMultiSendToAll.
        /// </summary>
        internal static string sendTypeSendToAll
        {
            get
            {
                return ResourceManager.GetString("sendTypeSendToAll", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SendTypeMultiSendToKnown.
        /// </summary>
        internal static string sendTypeSendToKnown
        {
            get
            {
                return ResourceManager.GetString("sendTypeSendToKnown", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SendTypeMultiSendToNew.
        /// </summary>
        internal static string sendTypeSendToNew
        {
            get
            {
                return ResourceManager.GetString("sendTypeSendToNew", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SendTypeStandard.
        /// </summary>
        internal static string sendTypeStandard
        {
            get
            {
                return ResourceManager.GetString("sendTypeStandard", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:.
        /// </summary>
        internal static string std
        {
            get
            {
                return ResourceManager.GetString("std", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:belongsTo.
        /// </summary>
        internal static string stdBelongsTo
        {
            get
            {
                return ResourceManager.GetString("stdBelongsTo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:contains.
        /// </summary>
        internal static string stdContains
        {
            get
            {
                return ResourceManager.GetString("stdContains", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:containsBaseBehavior.
        /// </summary>
        internal static string stdContainsBaseBehavior
        {
            get
            {
                return ResourceManager.GetString("stdContainsBaseBehavior", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:containsBehavior.
        /// </summary>
        internal static string stdContainsBehavior
        {
            get
            {
                return ResourceManager.GetString("stdContainsBehavior", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:containsPayloadDescription.
        /// </summary>
        internal static string stdContainsPayloadDescription
        {
            get
            {
                return ResourceManager.GetString("stdContainsPayloadDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:guardedBy.
        /// </summary>
        internal static string stdGuardedBy
        {
            get
            {
                return ResourceManager.GetString("stdGuardedBy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:guards.
        /// </summary>
        internal static string stdGuards
        {
            get
            {
                return ResourceManager.GetString("stdGuards", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:guardsBehavior.
        /// </summary>
        internal static string stdGuardsBehavior
        {
            get
            {
                return ResourceManager.GetString("stdGuardsBehavior", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:guardsState.
        /// </summary>
        internal static string stdGuardsState
        {
            get
            {
                return ResourceManager.GetString("stdGuardsState", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:hasBusinessDayDurationTimeOutTime.
        /// </summary>
        internal static string stdHasBusinessDayDurationTimeOutTime
        {
            get
            {
                return ResourceManager.GetString("stdHasBusinessDayDurationTimeOutTime", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:hasCalendarBasedFrequencyOrDate.
        /// </summary>
        internal static string stdHasCalendarBasedFrequencyOrDate
        {
            get
            {
                return ResourceManager.GetString("stdHasCalendarBasedFrequencyOrDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:hasCorrespondent.
        /// </summary>
        internal static string stdHasCorrespondent
        {
            get
            {
                return ResourceManager.GetString("stdHasCorrespondent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:hasDataDefintion.
        /// </summary>
        internal static string stdHasDataDefintion
        {
            get
            {
                return ResourceManager.GetString("stdHasDataDefintion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:hasDataMappingFunction.
        /// </summary>
        internal static string stdHasDataMappingFunction
        {
            get
            {
                return ResourceManager.GetString("stdHasDataMappingFunction", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:hasDataMappingString.
        /// </summary>
        internal static string stdHasDataMappingString
        {
            get
            {
                return ResourceManager.GetString("stdHasDataMappingString", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:hasDataType.
        /// </summary>
        internal static string stdHasDataType
        {
            get
            {
                return ResourceManager.GetString("stdHasDataType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:hasDayTimeDurationTimeOutTime.
        /// </summary>
        internal static string stdHasDayTimeDurationTimeOutTime
        {
            get
            {
                return ResourceManager.GetString("stdHasDayTimeDurationTimeOutTime", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:hasDurationTimeOutTime.
        /// </summary>
        internal static string stdHasDurationTimeOutTime
        {
            get
            {
                return ResourceManager.GetString("stdHasDurationTimeOutTime", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:hasEndState.
        /// </summary>
        internal static string stdHasEndState
        {
            get
            {
                return ResourceManager.GetString("stdHasEndState", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:hasExecutionMappingDefinition.
        /// </summary>
        internal static string stdHasExecutionMappingDefinition
        {
            get
            {
                return ResourceManager.GetString("stdHasExecutionMappingDefinition", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:hasFeelExpressionAsDataMapping.
        /// </summary>
        internal static string stdHasFeelExpressionAsDataMapping
        {
            get
            {
                return ResourceManager.GetString("stdHasFeelExpressionAsDataMapping", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:hasFunctionSpecification.
        /// </summary>
        internal static string stdHasFunctionSpecification
        {
            get
            {
                return ResourceManager.GetString("stdHasFunctionSpecification", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:hasHandlingStrategy.
        /// </summary>
        internal static string stdHasHandlingStrategy
        {
            get
            {
                return ResourceManager.GetString("stdHasHandlingStrategy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:hasIncomingMessageExchange.
        /// </summary>
        internal static string stdHasIncomingMessageExchange
        {
            get
            {
                return ResourceManager.GetString("stdHasIncomingMessageExchange", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:hasIncomingTransition.
        /// </summary>
        internal static string stdHasIncomingTransition
        {
            get
            {
                return ResourceManager.GetString("stdHasIncomingTransition", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:hasInitialState.
        /// </summary>
        internal static string stdHasInitialState
        {
            get
            {
                return ResourceManager.GetString("stdHasInitialState", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:hasInputPoolConstraint.
        /// </summary>
        internal static string stdHasInputPoolConstraint
        {
            get
            {
                return ResourceManager.GetString("stdHasInputPoolConstraint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:hasMaximumSubjectInstanceRestriction.
        /// </summary>
        internal static string stdhasInstanceRestriction
        {
            get
            {
                return ResourceManager.GetString("stdhasInstanceRestriction", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:hasLimit.
        /// </summary>
        internal static string stdHasLimit
        {
            get
            {
                return ResourceManager.GetString("stdHasLimit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:hasMessageType.
        /// </summary>
        internal static string stdHasMessageType
        {
            get
            {
                return ResourceManager.GetString("stdHasMessageType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:hasModelComponentID.
        /// </summary>
        internal static string stdHasModelComponentID
        {
            get
            {
                return ResourceManager.GetString("stdHasModelComponentID", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:hasModelComponentLabel.
        /// </summary>
        internal static string stdHasModelComponentLabel
        {
            get
            {
                return ResourceManager.GetString("stdHasModelComponentLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:hasMultiReceiveLowerBound.
        /// </summary>
        internal static string stdHasMultiReceiveLowerBound
        {
            get
            {
                return ResourceManager.GetString("stdHasMultiReceiveLowerBound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:hasMultiReceiveUpperBound.
        /// </summary>
        internal static string stdHasMultiReceiveUpperBound
        {
            get
            {
                return ResourceManager.GetString("stdHasMultiReceiveUpperBound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:hasMultiSendLowerBound.
        /// </summary>
        internal static string stdHasMultiSendLowerBound
        {
            get
            {
                return ResourceManager.GetString("stdHasMultiSendLowerBound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:hasMultiSendUpperBound.
        /// </summary>
        internal static string stdHasMultiSendUpperBound
        {
            get
            {
                return ResourceManager.GetString("stdHasMultiSendUpperBound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:hasOutgoingMessageExchange.
        /// </summary>
        internal static string stdHasOutgoingMessageExchange
        {
            get
            {
                return ResourceManager.GetString("stdHasOutgoingMessageExchange", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:hasOutgoingTransition.
        /// </summary>
        internal static string stdHasOutgoingTransition
        {
            get
            {
                return ResourceManager.GetString("stdHasOutgoingTransition", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:hasPriorityNumber.
        /// </summary>
        internal static string stdHasPriorityNumber
        {
            get
            {
                return ResourceManager.GetString("stdHasPriorityNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:hasReceiver.
        /// </summary>
        internal static string stdHasReceiver
        {
            get
            {
                return ResourceManager.GetString("stdHasReceiver", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:hasReceiveType.
        /// </summary>
        internal static string stdHasReceiveType
        {
            get
            {
                return ResourceManager.GetString("stdHasReceiveType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:hasReoccuranceFrequenyOrDate.
        /// </summary>
        internal static string stdHasReoccuranceFrequenyOrDate
        {
            get
            {
                return ResourceManager.GetString("stdHasReoccuranceFrequenyOrDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:hasSender.
        /// </summary>
        internal static string stdHasSender
        {
            get
            {
                return ResourceManager.GetString("stdHasSender", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:hasSendType.
        /// </summary>
        internal static string stdHasSendType
        {
            get
            {
                return ResourceManager.GetString("stdHasSendType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:hasSourceState.
        /// </summary>
        internal static string stdHasSourceState
        {
            get
            {
                return ResourceManager.GetString("stdHasSourceState", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:hasStartSubject.
        /// </summary>
        internal static string stdHasStartSubject
        {
            get
            {
                return ResourceManager.GetString("stdHasStartSubject", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:hasTargetState.
        /// </summary>
        internal static string stdHasTargetState
        {
            get
            {
                return ResourceManager.GetString("stdHasTargetState", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:hasTimeBasedReoccuranceFrequencyOrDate.
        /// </summary>
        internal static string stdHasTimeBasedReoccuranceFrequencyOrDate
        {
            get
            {
                return ResourceManager.GetString("stdHasTimeBasedReoccuranceFrequencyOrDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:hasTimeValue.
        /// </summary>
        internal static string stdHasTimeValue
        {
            get
            {
                return ResourceManager.GetString("stdHasTimeValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:hasToolSpecificDefinition.
        /// </summary>
        internal static string stdHasToolSpecificDefinition
        {
            get
            {
                return ResourceManager.GetString("stdHasToolSpecificDefinition", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:hasTransitionCondition.
        /// </summary>
        internal static string stdHasTransitionCondition
        {
            get
            {
                return ResourceManager.GetString("stdHasTransitionCondition", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:hasYearMonthDurationTimeOutTime.
        /// </summary>
        internal static string stdHasYearMonthDurationTimeOutTime
        {
            get
            {
                return ResourceManager.GetString("stdHasYearMonthDurationTimeOutTime", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:isOptionalToEndChoiceSegmentPath.
        /// </summary>
        internal static string stdIsOptionalToEndChoiceSegmentPath
        {
            get
            {
                return ResourceManager.GetString("stdIsOptionalToEndChoiceSegmentPath", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:isOptionalToStartChoiceSegmentPath.
        /// </summary>
        internal static string stdIsOptionalToStartChoiceSegmentPath
        {
            get
            {
                return ResourceManager.GetString("stdIsOptionalToStartChoiceSegmentPath", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to owl:NamedIndividual.
        /// </summary>
        internal static string stdNamedIndividual
        {
            get
            {
                return ResourceManager.GetString("stdNamedIndividual", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:receiver.
        /// </summary>
        internal static string stdReceiver
        {
            get
            {
                return ResourceManager.GetString("stdReceiver", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:ReceiveTypeMultiReceiveFromAllKnown.
        /// </summary>
        internal static string stdReceiveTypeReceiveFromAll
        {
            get
            {
                return ResourceManager.GetString("stdReceiveTypeReceiveFromAll", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:ReceiveTypeMultiReceiveFromKnwon.
        /// </summary>
        internal static string stdReceiveTypeReceiveFromKnown
        {
            get
            {
                return ResourceManager.GetString("stdReceiveTypeReceiveFromKnown", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:ReceiveTypeStandard.
        /// </summary>
        internal static string stdReceiveTypeStandard
        {
            get
            {
                return ResourceManager.GetString("stdReceiveTypeStandard", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:references.
        /// </summary>
        internal static string stdReferences
        {
            get
            {
                return ResourceManager.GetString("stdReferences", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:referencesMacroBehavior.
        /// </summary>
        internal static string stdReferencesMacroBehavior
        {
            get
            {
                return ResourceManager.GetString("stdReferencesMacroBehavior", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:requiresMessageSentFrom.
        /// </summary>
        internal static string stdRequiresMessageSentFrom
        {
            get
            {
                return ResourceManager.GetString("stdRequiresMessageSentFrom", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:requiresMessageSentTo.
        /// </summary>
        internal static string stdRequiresMessageSentTo
        {
            get
            {
                return ResourceManager.GetString("stdRequiresMessageSentTo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:requiresPerformedMessageExchange.
        /// </summary>
        internal static string stdRequiresPerformedMessageExchange
        {
            get
            {
                return ResourceManager.GetString("stdRequiresPerformedMessageExchange", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:requiresReceptionOfMessage.
        /// </summary>
        internal static string stdRequiresReceptionOfMessage
        {
            get
            {
                return ResourceManager.GetString("stdRequiresReceptionOfMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:requiresSendingOfMessage.
        /// </summary>
        internal static string stdRequiresSendingOfMessage
        {
            get
            {
                return ResourceManager.GetString("stdRequiresSendingOfMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:sender.
        /// </summary>
        internal static string stdSender
        {
            get
            {
                return ResourceManager.GetString("stdSender", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:SendTypeMultiSendToAll.
        /// </summary>
        internal static string stdSendTypeSendToAll
        {
            get
            {
                return ResourceManager.GetString("stdSendTypeSendToAll", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:SendTypeMultiSendToKnown.
        /// </summary>
        internal static string stdSendTypeSendToKnown
        {
            get
            {
                return ResourceManager.GetString("stdSendTypeSendToKnown", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:SendTypeMultiSendToNew.
        /// </summary>
        internal static string stdSendTypeSendToNew
        {
            get
            {
                return ResourceManager.GetString("stdSendTypeSendToNew", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:SendTypeStandard.
        /// </summary>
        internal static string stdSendTypeStandard
        {
            get
            {
                return ResourceManager.GetString("stdSendTypeStandard", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to standard-pass-ont:StartSubject.
        /// </summary>
        internal static string stdStartSubject
        {
            get
            {
                return ResourceManager.GetString("stdStartSubject", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to TimeBasedReminderTransition.
        /// </summary>
        internal static string TimeBasedReminderTransitionClassName
        {
            get
            {
                return ResourceManager.GetString("TimeBasedReminderTransitionClassName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to TimeBasedReminderTransitionCondition.
        /// </summary>
        internal static string TimeBasedReminderTransitionConditionClassName
        {
            get
            {
                return ResourceManager.GetString("TimeBasedReminderTransitionConditionClassName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to type.
        /// </summary>
        internal static string type
        {
            get
            {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to xsd:nonNegativeInteger.
        /// </summary>
        internal static string xsdDataTypeNonNegativeInt
        {
            get
            {
                return ResourceManager.GetString("xsdDataTypeNonNegativeInt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to xsd:positiveInteger.
        /// </summary>
        internal static string xsdDataTypePositiveInteger
        {
            get
            {
                return ResourceManager.GetString("xsdDataTypePositiveInteger", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to xsd:string.
        /// </summary>
        internal static string xsdDataTypeString
        {
            get
            {
                return ResourceManager.GetString("xsdDataTypeString", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to xsd:dayTimeDuration.
        /// </summary>
        internal static string xsdDayTimeDuration
        {
            get
            {
                return ResourceManager.GetString("xsdDayTimeDuration", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to xsd:yearMonthDuration.
        /// </summary>
        internal static string xsdYearMonthDuration
        {
            get
            {
                return ResourceManager.GetString("xsdYearMonthDuration", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to YearMonthTimerTransition.
        /// </summary>
        internal static string YearMonthTimerTransitionClassName
        {
            get
            {
                return ResourceManager.GetString("YearMonthTimerTransitionClassName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to YearMonthTimerTransitionCondition.
        /// </summary>
        internal static string YearMonthTimerTransitionConditionClassName
        {
            get
            {
                return ResourceManager.GetString("YearMonthTimerTransitionConditionClassName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to YearMonthTimerTransitionCondition.
        /// </summary>
        internal static string TimerTransitionConditionClassName
        {
            get
            {
                return ResourceManager.GetString("TimerTransitionConditionClassName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to YearMonthTimerTransitionCondition.
        /// </summary>
        internal static string ReminderEventTransitionConditionClassName
        {
            get
            {
                return ResourceManager.GetString("ReminderEventTransitionConditionClassName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to YearMonthTimerTransitionCondition.
        /// </summary>
        internal static string TimeTransitionConditionClassName
        {
            get
            {
                return ResourceManager.GetString("TimeTransitionConditionClassName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to YearMonthTimerTransitionCondition.
        /// </summary>
        internal static string xsdDuration
        {
            get
            {
                return ResourceManager.GetString("xsdDuration", resourceCulture);
            }
        }
    }
}
